import Head from 'next/head'
import Navbar from '../components/Navbar'
import HeroSection from '../components/HeroSection'
import FeaturesSection from '../components/FeaturesSection'
import FooterSection from '../components/FooterSection'
import LearnMoreSection from '../components/LearnMoreSection'

export default function Home() {
  return (
    <div className='text-gray-800'>
      <Head>
        <title>Next Landing / Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='h-screen bg-bottom bg-no-repeat bg-cover bg-hero-bg'>
        <div className='container mx-auto'>
          <Navbar />
          <HeroSection />
        </div>
      </header>
      <LearnMoreSection />
      <FeaturesSection />
      <FooterSection />
    </div>
  )
}
